config:
  send_anonymous_usage_stats: False
cmc:
  target: local
  outputs:
    local:
      type: fal
      db_profile: local_fal
    local_fal:
      type: redshift
      method: iam
      cluster_id: dev-cmc
      host: dev-cmc.cw28okmafrln.ap-southeast-2.redshift.amazonaws.com
      user: dbt-dev
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: "dbt_ci_{{ env_var('GITHUB_PR_NUMBER') }}"
      threads: 8
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600 # default 10 minutes
      retries: 1 # default 1 retry on error/timeout when opening connections
      ra3_node: true # enables cross-database sources
      autocreate: true

    ci:
      type: fal
      db_profile: ci_fal

    # CI/CD runs on schema dbt_ci
    ci_fal:
      type: redshift
      method: iam
      cluster_id: dev-cmc
      host: dev-cmc.cw28okmafrln.ap-southeast-2.redshift.amazonaws.com
      user: dbt
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: "dbt_ci_{{ env_var('GITHUB_PR_NUMBER') }}"
      threads: 8
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600 # default 10 minutes
      retries: 1 # default 1 retry on error/timeout when opening connections
      ra3_node: true # enables cross-database sources
      autocreate: true

    # Airflow/Steps run on schema dbt_cmc
    dev:
      type: fal
      db_profile: dev_fal
    dev_fal:
      type: redshift
      method: iam
      cluster_id: dev-cmc
      host: dev-cmc.cw28okmafrln.ap-southeast-2.redshift.amazonaws.com
      user: dbt
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: dbt_cmc
      threads: 32
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600 # default 10 minutes
      retries: 1 # default 1 retry on error/timeout when opening connections
      ra3_node: true # enables cross-database sources
      autocreate: true

    dev-local:
      type: redshift
      method: iam
      cluster_id: dev-cmc
      host: dev-cmc.cw28okmafrln.ap-southeast-2.redshift.amazonaws.com
      user: dbt-dev
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: dbt_dev
      threads: 32
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600 # default 10 minutes
      retries: 1 # default 1 retry on error/timeout when opening connections
      # ra3_node: true # enables cross-database sources
      autocreate: true

    nfr:
      type: fal
      db_profile: nfr_fal
    nfr_fal:
      type: redshift
      method: iam
      cluster_id: nfr-cmc
      host: nfr-cmc.cw28okmafrln.ap-southeast-2.redshift.amazonaws.com
      user: dbt
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: dbt_cmc
      threads: 32
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600 # default 10 minutes
      retries: 1 # default 1 retry on error/timeout when opening connections
      ra3_node: true # enables cross-database sources
      autocreate: true

    uat:
      type: fal
      db_profile: uat_fal
    uat_fal:
      type: redshift
      method: iam
      cluster_id: uat-cmc
      host: uat-cmc.cw28okmafrln.ap-southeast-2.redshift.amazonaws.com
      user: dbt
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: dbt_cmc
      threads: 32
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600 # default 10 minutes
      retries: 1 # default 1 retry on error/timeout when opening connections
      ra3_node: true # enables cross-database sources
      autocreate: true
    prod:
      type: fal
      db_profile: prod_fal
    prod_fal:
      type: redshift
      method: iam
      cluster_id: prod-cmc
      host: prod-cmc.cy9xb6hj4lhi.ap-southeast-2.redshift.amazonaws.com
      user: dbt
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: 5439
      dbname: cmc_db
      schema: dbt_cmc
      threads: 32
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 600
      retries: 2 # default 1 retry on error/timeout when opening connections
      ra3_node: true # enables cross-database sources
      autocreate: true
# GRANT SELECT ON ALL TABLES IN SCHEMA awcdata TO iam:dbt;
# GRANT SELECT ON ALL TABLES IN SCHEMA dbt_cmc TO iam:dbt;
# GRANT ALL ON DATABASE cmc_db TO iam:dbt;
# GRANT USAGE ON SCHEMA awcdata TO iam:dbt;
# GRANT ALL ON SCHEMA dbt_cmc TO iam:airfldbtow;
