config:
  send_anonymous_usage_stats: false

jaffle_shop:
  target: jaffle
  outputs:
    jaffle:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | as_number }}"
      user: "{{ env_var('PGUSER') }}"
      pass: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      sslmode: disable
      schema: "{{ env_var('SEED_SCHEMA', 'jaffle') }}"
datapai:
  target: dev-local
  outputs:

    # CI/CD runs on schema dbt_ci
    ci_fal:
      type: redshift
      method: database
      cluster_id: redshift-cluster-1
      host: "{{ env_var('REDSHIFT_HOST') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PWD') }}"   
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: "{{ env_var('REDSHIFT_PORT')| as_number }}"
      dbname: dev
      schema: datapai
      threads: 8
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 10 # default 10 seconds
      retries: 1 # default 1 retry on error/timeout when opening connections
      autocreate: true
      ra3_node: false


    dev-local:
      type: redshift
      method: database
      cluster_id: redshift-cluster-1
      host: "{{ env_var('REDSHIFT_HOST') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PWD') }}"   
      region: ap-southeast-2
      iam_duration_seconds: 3600
      port: "{{ env_var('REDSHIFT_PORT') | as_number }}"
      dbname: dev
      schema: datapai
      threads: 4
      keepalives_idle: 240 # default 240 seconds
      connect_timeout: 10 # default 10 seconds
      retries: 1 # default 1 retry on error/timeout when opening connections
      autocreate: true
      ra3_node: false
    logs:
    # Enable logging for dbt-rpc
    dbt_rpc: debug  # Set the log level to debug for dbt-rpc.


