{{ config(
    materialized    = 'table',
    schema          = 'STOCK_MARTS',
    table_format    = 'iceberg',
    external_volume = 'DATAPAI_S3_VOL',
    tags            = ["fact", "stock_ai"]
) }}

with price_data as (
    select
        ticker,
        exchange,
        trade_date,
        close,
        volume,
        sma_5,
        sma_200,
        volatility_20d,
        rsi_14,
        kdj_k,
        pivot_pp,
        obv_trend,
        lag(close, 1) over (partition by ticker, exchange order by trade_date) as close_lag_1d,
        lag(close, 5) over (partition by ticker, exchange order by trade_date) as close_lag_5d,
        lag(close, 21) over (partition by ticker, exchange order by trade_date) as close_lag_1m,
        lag(close, 63) over (partition by ticker, exchange order by trade_date) as close_lag_3m,
        lag(close, 126) over (partition by ticker, exchange order by trade_date) as close_lag_6m,
        lag(close, 252) over (partition by ticker, exchange order by trade_date) as close_lag_1y,
        max(close) over (partition by ticker, exchange order by trade_date rows between 252 preceding and current row) as high_52w,
        min(close) over (partition by ticker, exchange order by trade_date rows between 252 preceding and current row) as low_52w,
        avg(close) over (partition by ticker, exchange order by trade_date rows between 19 preceding and current row) as sma_20,
        avg(close) over (partition by ticker, exchange order by trade_date rows between 49 preceding and current row) as sma_50,
        avg(close) over (partition by ticker, exchange order by trade_date rows between 9 preceding and current row) as sma_10,
        avg(close) over (partition by ticker, exchange order by trade_date rows between 29 preceding and current row) as sma_30,
        avg(volume) over (partition by ticker, exchange order by trade_date rows between 19 preceding and current row) as avg_volume_20d,
        avg(volume) over (partition by ticker, exchange order by trade_date rows between 4 preceding and current row) as avg_volume_5d,
        avg(volume) over (partition by ticker, exchange order by trade_date rows between 9 preceding and current row) as avg_volume_10d,
        row_number() over (partition by ticker, exchange order by trade_date desc) as rn
    from {{ ref('int_price_with_indicators') }}
),

latest_metrics as (
    select
        ticker,
        exchange,
        trade_date,
        close as latest_close,
        volume as latest_volume,
        (close - close_lag_1d) / nullif(close_lag_1d, 0) as change_1d_pct,
        (close - close_lag_5d) / nullif(close_lag_5d, 0) as change_5d_pct,
        (close - close_lag_1m) / nullif(close_lag_1m, 0) as change_1m_pct,
        (close - close_lag_3m) / nullif(close_lag_3m, 0) as change_3m_pct,
        (close - close_lag_6m) / nullif(close_lag_6m, 0) as change_6m_pct,
        (close - close_lag_1y) / nullif(close_lag_1y, 0) as change_1y_pct,
        high_52w,
        low_52w,
        (close - high_52w) / nullif(high_52w, 0) as pct_from_52w_high,
        (close - low_52w) / nullif(low_52w, 0) as pct_from_52w_low,
        sma_20,
        sma_50,
        sma_200,
        (close - sma_20) / nullif(sma_20, 0) as price_vs_sma20_pct,
        (close - sma_50) / nullif(sma_50, 0) as price_vs_sma50_pct,
        (close - sma_200) / nullif(sma_200, 0) as price_vs_sma200_pct,
        case when sma_50 > sma_200 then true else false end as golden_cross,
        case when sma_50 < sma_200 then true else false end as death_cross,
        avg_volume_20d,
        volume / nullif(avg_volume_20d, 0) as volume_ratio,
        volatility_20d,
        rsi_14,
        sma_5,
        sma_10,
        sma_30,
        (close - sma_5) / nullif(sma_5, 0) as price_vs_sma5_pct,
        (close - sma_10) / nullif(sma_10, 0) as price_vs_sma10_pct,
        (close - sma_30) / nullif(sma_30, 0) as price_vs_sma30_pct,
        kdj_k,
        pivot_pp,
        obv_trend,
        avg_volume_5d,
        avg_volume_10d
    from price_data
    where rn = 1
),

final as (
    select
        m.ticker,
        m.exchange,
        m.latest_close,
        m.latest_volume,
        m.trade_date,
        m.change_1d_pct,
        m.change_5d_pct,
        m.change_1m_pct,
        m.change_3m_pct,
        m.change_6m_pct,
        m.change_1y_pct,
        m.high_52w,
        m.low_52w,
        m.pct_from_52w_high,
        m.pct_from_52w_low,
        m.sma_20,
        m.sma_50,
        m.sma_200,
        m.price_vs_sma20_pct,
        m.price_vs_sma50_pct,
        m.price_vs_sma200_pct,
        m.golden_cross,
        m.death_cross,
        m.avg_volume_20d,
        m.volume_ratio,
        m.volatility_20d,
        m.rsi_14,
        cast(current_timestamp() as timestamp_ntz(6)) as computed_at,
        m.sma_5,
        m.sma_10,
        m.sma_30,
        m.price_vs_sma5_pct,
        m.price_vs_sma10_pct,
        m.price_vs_sma30_pct,
        cast(null as double) as macd_line,
        cast(null as double) as macd_signal,
        cast(null as double) as macd_histogram,
        cast(null as varchar) as macd_trend,
        m.kdj_k,
        cast(null as double) as kdj_d,
        cast(null as double) as kdj_j,
        cast(null as varchar) as kdj_signal,
        cast(null as double) as bb_upper,
        cast(null as double) as bb_middle,
        cast(null as double) as bb_lower,
        cast(null as double) as bb_pct_b,
        cast(null as double) as bb_width,
        m.pivot_pp,
        cast(null as double) as pivot_r1,
        cast(null as double) as pivot_r2,
        cast(null as double) as pivot_s1,
        cast(null as double) as pivot_s2,
        m.obv_trend,
        m.avg_volume_5d,
        m.avg_volume_10d
    from latest_metrics m
    left join {{ ref('dim_ticker') }} t on m.ticker = t.ticker and m.exchange = t.exchange
    left join {{ ref('dim_exchange') }} e on m.exchange = e.exchange
)

select * from final
