{{ config(
    materialized    = 'table',
    schema          = 'STOCK_MARTS',
    table_format    = 'iceberg',
    external_volume = 'DATAPAI_S3_VOL',
    tags            = ["fact", "stock_ai"]
) }}

with latest_indicators as (
    select
        *
    from {{ ref('int_price_with_indicators') }}
    qualify row_number() over (partition by ticker, exchange order by trade_date desc) = 1
),

joined as (
    select
        li.ticker,
        li.exchange,
        li.close_usd as latest_close,
        li.volume as latest_volume,
        li.trade_date,
        li.change_1d_pct,
        li.change_5d_pct,
        li.change_1m_pct,
        li.change_3m_pct,
        li.change_6m_pct,
        li.change_1y_pct,
        li.high_52w,
        li.low_52w,
        li.pct_from_52w_high,
        li.pct_from_52w_low,
        li.sma_20,
        li.sma_50,
        li.sma_200,
        case when li.sma_20 != 0 then (li.close_usd - li.sma_20) / li.sma_20 else null end as price_vs_sma20_pct,
        case when li.sma_50 != 0 then (li.close_usd - li.sma_50) / li.sma_50 else null end as price_vs_sma50_pct,
        case when li.sma_200 != 0 then (li.close_usd - li.sma_200) / li.sma_200 else null end as price_vs_sma200_pct,
        case when li.sma_50 > li.sma_200 then true else false end as golden_cross,
        case when li.sma_50 < li.sma_200 then true else false end as death_cross,
        li.avg_volume_20d,
        case when li.avg_volume_20d != 0 then li.volume / li.avg_volume_20d else null end as volume_ratio,
        li.volatility_20d,
        li.rsi_14,
        cast(current_timestamp() as timestamp_ntz(6)) as computed_at,
        li.sma_5,
        li.sma_10,
        li.sma_30,
        case when li.sma_5 != 0 then (li.close_usd - li.sma_5) / li.sma_5 else null end as price_vs_sma5_pct,
        case when li.sma_10 != 0 then (li.close_usd - li.sma_10) / li.sma_10 else null end as price_vs_sma10_pct,
        case when li.sma_30 != 0 then (li.close_usd - li.sma_30) / li.sma_30 else null end as price_vs_sma30_pct,
        li.macd_line,
        li.macd_signal,
        li.macd_histogram,
        case when li.macd_line > li.macd_signal then 'BULLISH' else 'BEARISH' end as macd_trend,
        li.kdj_k,
        li.kdj_d,
        li.kdj_j,
        case when li.kdj_j > 80 then 'OVERBOUGHT' when li.kdj_j < 20 then 'OVERSOLD' else 'NEUTRAL' end as kdj_signal,
        li.bb_upper,
        li.bb_middle,
        li.bb_lower,
        li.bb_pct_b,
        li.bb_width,
        li.pivot_pp,
        li.pivot_r1,
        li.pivot_r2,
        li.pivot_s1,
        li.pivot_s2,
        li.obv_trend,
        li.avg_volume_5d,
        li.avg_volume_10d,
        t.ticker_key,
        e.exchange_key
    from latest_indicators li
    left join {{ ref('dim_ticker') }} t 
        on li.ticker = t.yf_symbol 
        and li.exchange = t.exchange
    left join {{ ref('dim_exchange') }} e 
        on li.exchange = e.exchange
)

select
    ticker,
    exchange,
    latest_close,
    latest_volume,
    trade_date,
    change_1d_pct,
    change_5d_pct,
    change_1m_pct,
    change_3m_pct,
    change_6m_pct,
    change_1y_pct,
    high_52w,
    low_52w,
    pct_from_52w_high,
    pct_from_52w_low,
    sma_20,
    sma_50,
    sma_200,
    price_vs_sma20_pct,
    price_vs_sma50_pct,
    price_vs_sma200_pct,
    golden_cross,
    death_cross,
    avg_volume_20d,
    volume_ratio,
    volatility_20d,
    rsi_14,
    computed_at,
    sma_5,
    sma_10,
    sma_30,
    price_vs_sma5_pct,
    price_vs_sma10_pct,
    price_vs_sma30_pct,
    macd_line,
    macd_signal,
    macd_histogram,
    macd_trend,
    kdj_k,
    kdj_d,
    kdj_j,
    kdj_signal,
    bb_upper,
    bb_middle,
    bb_lower,
    bb_pct_b,
    bb_width,
    pivot_pp,
    pivot_r1,
    pivot_r2,
    pivot_s1,
    pivot_s2,
    obv_trend,
    avg_volume_5d,
    avg_volume_10d,
    ticker_key,
    exchange_key
from joined
