name: dbt close
on:
  pull_request:
    types: [closed]
env:
  env: nonprod
  STAGE: ci
  ACCOUNT_ID: 073596371268
  ACTION: delete
  PRODUCT: datapai
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
  REGION: ap-southeast-2
  SERVICE: data-pipeline
  PR_NUMBER: ${{github.event.pull_request.number}}
jobs:
  clean:
    name: dbt
    runs-on: ["self-hosted", "ubuntu", "x64", "apac", "nonprod"]
    environment: nonprod
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: pip3 install redshift_connector
      - run: python3 clean_pr.py
