name: dbt PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
# concurrency: infra-dev
concurrency: ci-${{ github.ref }}
jobs:
  cicd:
    uses: ./.github/workflows/dbt.yml
    with:
      account_id: "073596371268"
      stage: ci
      env: nonprod
      env_name: dev
      slim_ci: true
      bucket_name: airflow-dag-s3
      dbt_bucket: "s3://airflow-dag-s3/dag/dbt/bi_team/"
      redshift_database: cmc_db
      tf_var_role_name: apacdata-pipeline_cd-nonprod
      github_runner: '["self-hosted", "ubuntu", "x64", "apac", "nonprod"]'
      pr_number: ${{github.event.pull_request.number}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
