name: dbt dev
on:
  push:
    branches: [master]
concurrency: infra-dev
jobs:
  cicd:
    uses: ./.github/workflows/dbt.yml
    with:
      account_id: "073596371268"
      stage: dev
      env: nonprod
      env_name: dev
      slim_ci: true
      bucket_name: airflow-dag-s3
      dbt_bucket: "s3://airflow-dag-s3/dag/dbt/bi_team/"
      github_runner: '["self-hosted", "ubuntu", "x64", "apac", "nonprod"]'ß
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
